export const INCREMENT_COUNTER = `INCREMENT_COUNTER`;

export const DECREMENT_COUNTER = `DECREMENT_COUNTER`;

export const RESET_COUNTER = `RESET_COUNTER`;
export const ADD_TODO= `ADD_TODO`;
export const EDIT_TODO = `EDIT_TODO`;
export const CHANGE_STATUS = `CHANGE_STATUS`;
export const DELETE_TODO= `DELETE_TODO`;